sources:
  - format: xml
    sourceName: TagValidationSource
    filePath: input/nested-sample.xml
    rootElement: TagValidationList
    recordElement: TVLTagDetails
    flatteningStrategy: NestedXml
    modelDefinitionPath: definitions/nested-source-model.yaml
  - format: csv
    sourceName: TagValidationCsvIntermediate
    filePath: output/intermediate/tag-validation-intermediate.csv
    delimiter: ","
    skipHeader: true
    fields:
      - name: homeAgencyId
        type: String
      - name: tagAgencyId
        type: String
      - name: tagSerialNumber
        type: String
      - name: plateNumber
        type: String
      - name: plateCountry
        type: String
      - name: plateState
        type: String
      - name: accountNumber
        type: String

