name: xml-nested-to-csv-tag-validation
sourceConfigPath: source-config-proof.yaml
targetConfigPath: target-config-proof-flatMapped.yaml
processorConfigPath: processor-config-proof-flatMapped.yaml
steps:
  - name: nested-tag-validation-proof-flatmapped-step
    source: TagValidationSource
    target: TagValidationCsv



