sources:
  - format: xml
    sourceName: TagValidationSource
    filePath: input/tag-validation-sample.xml
    archive:
      enabled: false
      successPath: output/archive/success/
      namePattern: "{originalName}-{timestamp}"
    rootElement: TagValidationList
    recordElement: TVLTagDetails
    flatteningStrategy: NestedXml
    modelDefinitionPath: definitions/nested-source-model.yaml

