package com.etl.common.util;

import com.etl.config.source.SourceConfig;
import com.etl.config.source.XmlSourceConfig;
import com.etl.config.target.TargetConfig;
import com.etl.config.target.XmlTargetConfig;

import java.util.Locale;
import java.util.regex.Pattern;

/**
 * Shared naming policy for generated source/target model classes.
 *
 * <p>Compatibility note: the derived <LogicalName><Shape> contract is applied for
 * job-scoped generated packages, while legacy authored packages continue to use the
 * historical simple-name behavior until the bridge is removed.</p>
 */
public final class GeneratedModelNamingPolicy {

    private static final Pattern NON_IDENTIFIER_CHARS = Pattern.compile("[^a-zA-Z0-9_]");
    private static final String JOB_SCOPED_PACKAGE_PREFIX = "com.etl.generated.job.";
    private static final String GENERATED_SOURCE_HEADER = "Generated by OneFlow. Do not edit manually.";

    private GeneratedModelNamingPolicy() {
    }

    public static String generatedSourceHeader() {
        return GENERATED_SOURCE_HEADER;
    }

    public static boolean usesDerivedJobScopedNaming(String packageName) {
        return packageName != null && packageName.startsWith(JOB_SCOPED_PACKAGE_PREFIX);
    }

    public static String resolveSourceSimpleClassName(SourceConfig sourceConfig) {
        if (sourceConfig instanceof XmlSourceConfig xmlSourceConfig) {
            return usesDerivedJobScopedNaming(xmlSourceConfig.getPackageName())
                    ? resolveXmlRecordSimpleClassName(xmlSourceConfig.getSourceName())
                    : requireLegacySimpleName(xmlSourceConfig.getRecordElement(), "recordElement", "XML source", xmlSourceConfig.getSourceName());
        }

        return usesDerivedJobScopedNaming(sourceConfig.getPackageName())
                ? resolveFlatSimpleClassName(sourceConfig.getSourceName())
                : requireLegacySimpleName(sourceConfig.getSourceName(), "sourceName", "source", sourceConfig.getSourceName());
    }

    public static String resolveSourceRootSimpleClassName(SourceConfig sourceConfig) {
        if (sourceConfig instanceof XmlSourceConfig xmlSourceConfig) {
            return usesDerivedJobScopedNaming(xmlSourceConfig.getPackageName())
                    ? resolveXmlRootSimpleClassName(xmlSourceConfig.getSourceName())
                    : requireLegacySimpleName(xmlSourceConfig.getRootElement(), "rootElement", "XML source", xmlSourceConfig.getSourceName());
        }
        return resolveSourceSimpleClassName(sourceConfig);
    }

    public static String resolveTargetWriteSimpleClassName(TargetConfig targetConfig) {
        if (targetConfig instanceof XmlTargetConfig xmlTargetConfig) {
            return usesDerivedJobScopedNaming(xmlTargetConfig.getPackageName())
                    ? resolveXmlRootSimpleClassName(xmlTargetConfig.getTargetName())
                    : requireLegacySimpleName(xmlTargetConfig.getRootElement(), "rootElement", "XML target", xmlTargetConfig.getTargetName());
        }

        return usesDerivedJobScopedNaming(targetConfig.getPackageName())
                ? resolveFlatSimpleClassName(targetConfig.getTargetName())
                : requireLegacySimpleName(targetConfig.getTargetName(), "targetName", "target", targetConfig.getTargetName());
    }

    public static String resolveTargetProcessingSimpleClassName(TargetConfig targetConfig) {
        if (targetConfig instanceof XmlTargetConfig xmlTargetConfig) {
            return usesDerivedJobScopedNaming(xmlTargetConfig.getPackageName())
                    ? resolveXmlRecordSimpleClassName(xmlTargetConfig.getTargetName())
                    : requireLegacySimpleName(xmlTargetConfig.getRecordElement(), "recordElement", "XML target", xmlTargetConfig.getTargetName());
        }

        return usesDerivedJobScopedNaming(targetConfig.getPackageName())
                ? resolveFlatSimpleClassName(targetConfig.getTargetName())
                : requireLegacySimpleName(targetConfig.getTargetName(), "targetName", "target", targetConfig.getTargetName());
    }

    public static String resolveFlatSimpleClassName(String logicalName) {
        return normalizeLogicalName(logicalName) + "Model";
    }

    public static String resolveXmlRecordSimpleClassName(String logicalName) {
        return normalizeLogicalName(logicalName) + "XmlRecord";
    }

    public static String resolveXmlRootSimpleClassName(String logicalName) {
        return normalizeLogicalName(logicalName) + "XmlRoot";
    }

    public static String resolveWrapperFieldName(String packageName, String recordElement, String recordClassName) {
        String accessorBase = resolveWrapperAccessorBase(packageName, recordElement, recordClassName);
        return Character.toLowerCase(accessorBase.charAt(0)) + accessorBase.substring(1);
    }

    public static String resolveWrapperAccessorBase(String packageName, String recordElement, String recordClassName) {
        if (usesDerivedJobScopedNaming(packageName)) {
            return requireLegacySimpleName(recordClassName, "recordClassName", "generated XML wrapper", recordClassName);
        }
        return requireLegacySimpleName(recordElement, "recordElement", "XML wrapper", recordClassName);
    }

    public static String normalizeLogicalName(String logicalName) {
        if (logicalName == null || logicalName.isBlank()) {
            throw new IllegalArgumentException("Generated model naming requires a non-blank logical config name.");
        }

        String cleaned = NON_IDENTIFIER_CHARS.matcher(logicalName.trim()).replaceAll(" ");
        String[] parts = cleaned.split("\\s+");
        StringBuilder result = new StringBuilder();
        for (String part : parts) {
            if (part.isBlank()) {
                continue;
            }
            result.append(part.substring(0, 1).toUpperCase(Locale.ROOT));
            if (part.length() > 1) {
                result.append(part.substring(1));
            }
        }

        if (result.isEmpty()) {
            throw new IllegalArgumentException("Generated model naming could not derive a Java class name from logical config name '" + logicalName + "'.");
        }

        if (!Character.isJavaIdentifierStart(result.charAt(0))) {
            result.insert(0, 'X');
        }
        for (int i = 1; i < result.length(); i++) {
            if (!Character.isJavaIdentifierPart(result.charAt(i))) {
                throw new IllegalArgumentException("Generated model naming produced an invalid Java identifier from logical config name '" + logicalName + "'.");
            }
        }
        return result.toString();
    }

    private static String requireLegacySimpleName(String value, String fieldName, String configType, String configName) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(configType + " config '" + defaultConfigName(configName)
                    + "' must define a non-blank " + fieldName + " before generated model class resolution.");
        }
        String trimmed = value.trim();
        if (!isJavaIdentifier(trimmed)) {
            throw new IllegalArgumentException(configType + " config '" + defaultConfigName(configName) + "' has invalid "
                    + fieldName + "='" + trimmed + "'. Expected a Java identifier-compatible generated class name segment.");
        }
        return trimmed;
    }

    private static String defaultConfigName(String configName) {
        return configName == null || configName.isBlank() ? "unnamed" : configName.trim();
    }

    private static boolean isJavaIdentifier(String value) {
        if (value == null || value.isBlank()) {
            return false;
        }
        if (!Character.isJavaIdentifierStart(value.charAt(0))) {
            return false;
        }
        for (int i = 1; i < value.length(); i++) {
            if (!Character.isJavaIdentifierPart(value.charAt(i))) {
                return false;
            }
        }
        return true;
    }
}
