sources:
  - format: csv
    sourceName: Events
    packageName: com.etl.generated.job.csvvalidationrejectarchive.source
    filePath: input/events-validation-input.csv
    delimiter: ","
    archive:
      enabled: true
      successPath: output/archive/success/
      namePattern: "{originalName}-{timestamp}"
    fields:
      - name: id
        type: String
      - name: eventTime
        type: String
      - name: description
        type: String
