targets:
  - format: xml
    targetName: CustomersNestedXml
    filePath: output/customers-nested.xml
    rootElement: Customers
    recordElement: CustomerRecord
    modelDefinitionPath: definitions/nested-target-model.yaml

