spring.profiles.active=dev

# External ETL configuration paths
etl.config.source=C:/ETLDemo/config/source-config.yaml
etl.config.target=C:/ETLDemo/config/target-config.yaml
etl.config.processor=C:/ETLDemo/config/processor-config.yaml

# Model paths configuration
model.paths.sourceDir=src/main/java/com/etl/model/source
model.paths.targetDir=src/main/java/com/etl/model/target
model.paths.sourceClassDir=target/classes/com/etl/model/source
model.paths.targetClassDir=target/classes/com/etl/model/target

# Enable debug logging for BatchConfig
logging.level.com.etl.config.BatchConfig=DEBUG
# Optionally, enable debug for the whole project
# logging.level.com.etl=DEBUG
