sources:
  - format: csv
    sourceName: Customers
    filePath: src/main/resources/demo-input/Customers.csv
    delimiter: ","
    fields:
      - name: id
        type: int
      - name: name
        type: String
      - name: email
        type: String
  - format: csv
    sourceName: Department
    filePath: src/main/resources/demo-input/Department.csv
    delimiter: ","
    fields:
      - name: id
        type: int
      - name: name
        type: String
