-- Bootstrap script for Spring Batch metadata tables on SQL Server.
-- Usage example:
--   sqlcmd -S localhost -U sa -P <password> -i scripts/sql/mssql/spring-batch-metadata.sql
-- Token {{CONTROLPLANE_DATABASE_NAME}} is materialized by scripts/setup-controlplane-mssql.ps1.

IF DB_ID(N'{{CONTROLPLANE_DATABASE_NAME}}') IS NULL
BEGIN
    EXEC ('CREATE DATABASE [{{CONTROLPLANE_DATABASE_NAME}}]');
END;
GO

USE [{{CONTROLPLANE_DATABASE_NAME}}];
GO

IF OBJECT_ID(N'dbo.BATCH_JOB_INSTANCE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BATCH_JOB_INSTANCE (
        JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
        VERSION BIGINT NULL,
        JOB_NAME NVARCHAR(100) NOT NULL,
        JOB_KEY NVARCHAR(32) NOT NULL,
        CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
    );
END;
GO

IF OBJECT_ID(N'dbo.BATCH_JOB_EXECUTION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BATCH_JOB_EXECUTION (
        JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
        VERSION BIGINT NULL,
        JOB_INSTANCE_ID BIGINT NOT NULL,
        CREATE_TIME DATETIME2 NOT NULL,
        START_TIME DATETIME2 NULL,
        END_TIME DATETIME2 NULL,
        STATUS NVARCHAR(10) NULL,
        EXIT_CODE NVARCHAR(2500) NULL,
        EXIT_MESSAGE NVARCHAR(MAX) NULL,
        LAST_UPDATED DATETIME2 NULL,
        CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
            REFERENCES dbo.BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
    );
END;
GO

IF OBJECT_ID(N'dbo.BATCH_JOB_EXECUTION_PARAMS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BATCH_JOB_EXECUTION_PARAMS (
        JOB_EXECUTION_ID BIGINT NOT NULL,
        PARAMETER_NAME NVARCHAR(100) NOT NULL,
        PARAMETER_TYPE NVARCHAR(100) NOT NULL,
        PARAMETER_VALUE NVARCHAR(2500) NULL,
        IDENTIFYING CHAR(1) NOT NULL,
        CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
            REFERENCES dbo.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
    );
END;
GO

IF OBJECT_ID(N'dbo.BATCH_STEP_EXECUTION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BATCH_STEP_EXECUTION (
        STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
        VERSION BIGINT NOT NULL,
        STEP_NAME NVARCHAR(100) NOT NULL,
        JOB_EXECUTION_ID BIGINT NOT NULL,
        CREATE_TIME DATETIME2 NOT NULL,
        START_TIME DATETIME2 NULL,
        END_TIME DATETIME2 NULL,
        STATUS NVARCHAR(10) NULL,
        COMMIT_COUNT BIGINT NULL,
        READ_COUNT BIGINT NULL,
        FILTER_COUNT BIGINT NULL,
        WRITE_COUNT BIGINT NULL,
        READ_SKIP_COUNT BIGINT NULL,
        WRITE_SKIP_COUNT BIGINT NULL,
        PROCESS_SKIP_COUNT BIGINT NULL,
        ROLLBACK_COUNT BIGINT NULL,
        EXIT_CODE NVARCHAR(2500) NULL,
        EXIT_MESSAGE NVARCHAR(MAX) NULL,
        LAST_UPDATED DATETIME2 NULL,
        CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
            REFERENCES dbo.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
    );
END;
GO

IF OBJECT_ID(N'dbo.BATCH_STEP_EXECUTION_CONTEXT', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BATCH_STEP_EXECUTION_CONTEXT (
        STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
        SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
        SERIALIZED_CONTEXT NVARCHAR(MAX) NULL,
        CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
            REFERENCES dbo.BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
    );
END;
GO

IF OBJECT_ID(N'dbo.BATCH_JOB_EXECUTION_CONTEXT', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BATCH_JOB_EXECUTION_CONTEXT (
        JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
        SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
        SERIALIZED_CONTEXT NVARCHAR(MAX) NULL,
        CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
            REFERENCES dbo.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'JOB_EXECUTION_INSTANCE_IDX' AND object_id = OBJECT_ID(N'dbo.BATCH_JOB_EXECUTION'))
    CREATE INDEX JOB_EXECUTION_INSTANCE_IDX ON dbo.BATCH_JOB_EXECUTION (JOB_INSTANCE_ID);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'JOB_EXECUTION_STATUS_IDX' AND object_id = OBJECT_ID(N'dbo.BATCH_JOB_EXECUTION'))
    CREATE INDEX JOB_EXECUTION_STATUS_IDX ON dbo.BATCH_JOB_EXECUTION (STATUS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'STEP_EXECUTION_JOB_EXECUTION_IDX' AND object_id = OBJECT_ID(N'dbo.BATCH_STEP_EXECUTION'))
    CREATE INDEX STEP_EXECUTION_JOB_EXECUTION_IDX ON dbo.BATCH_STEP_EXECUTION (JOB_EXECUTION_ID);
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.sequences
    WHERE name = N'BATCH_JOB_SEQ'
      AND schema_id = SCHEMA_ID(N'dbo')
)
BEGIN
    CREATE SEQUENCE dbo.BATCH_JOB_SEQ
        AS BIGINT
        START WITH 1
        INCREMENT BY 1
        NO CYCLE
        NO CACHE;
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.sequences
    WHERE name = N'BATCH_JOB_EXECUTION_SEQ'
      AND schema_id = SCHEMA_ID(N'dbo')
)
BEGIN
    CREATE SEQUENCE dbo.BATCH_JOB_EXECUTION_SEQ
        AS BIGINT
        START WITH 1
        INCREMENT BY 1
        NO CYCLE
        NO CACHE;
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.sequences
    WHERE name = N'BATCH_STEP_EXECUTION_SEQ'
      AND schema_id = SCHEMA_ID(N'dbo')
)
BEGIN
    CREATE SEQUENCE dbo.BATCH_STEP_EXECUTION_SEQ
        AS BIGINT
        START WITH 1
        INCREMENT BY 1
        NO CYCLE
        NO CACHE;
END;
GO


