name: xml-to-csv-events-transform-showcase
isActive: true
sourceConfigPath: source-config.yaml
targetConfigPath: target-config.yaml
processorConfigPath: processor-config.yaml
recoveryPolicy: rerun-from-start
steps:
  - name: events-transform-showcase-step
    source: Events
    target: EventsCsv

