name: relational-to-relational
sourceConfigPath: source-config.yaml
targetConfigPath: target-config.yaml
processorConfigPath: processor-config.yaml
steps:
  - name: customers-relational-step
    source: Customers
    target: CustomersSql
