targets:
  - format: relational
    targetName: CustomersSql
    packageName: com.etl.model.target
    schema: dbo
    table: Customers
    writeMode: insert
    batchSize: 100
    connection:
      vendor: sqlserver
      jdbcUrl: jdbc:sqlserver://192.168.50.195:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=true
      schema: dbo
      username: TESTDB
      password: Test@4321
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    fields:
      - name: id
        type: int
      - name: name
        type: String
      - name: email
        type: String


