name: customer-load-skip-policy-category
isActive: true
sourceConfigPath: source-config.yaml
targetConfigPath: target-config.yaml
processorConfigPath: processor-config.yaml
steps:
  - name: customers-step
    source: Customers
    target: Customers
    skipPolicy:
      enabled: true
      skipLimit: 10
      skippableCategories:
        - runtime
    retryPolicy:
      enabled: false

