sources:
  - format: csv
    sourceName: Customers
    filePath: src/main/resources/demo-input/Customers.csv
    delimiter: ","
    parser:
      quoteCharacter: '"'
    fields:
      - name: id
        type: int
      - name: name
        type: String
      - name: email
        type: String

