name: csv-to-nested-xml
sourceConfigPath: source-config.yaml
targetConfigPath: target-config.yaml
processorConfigPath: processor-config.yaml
steps:
  - name: customers-to-nested-xml-step
    source: CustomersCsv
    target: CustomersNestedXml

