sources:
  - format: csv
    sourceName: Department
    filePath: src/main/resources/demo-input/Department.csv
    delimiter: ","
    fields:
      - name: id
        type: int
      - name: name
        type: String

