targets:
  - format: xml
    packageName: com.etl.generated.job.departmentload.target
    filePath: output/departments.xml
    targetName: Departments
    rootElement: Departments
    recordElement: Department
    fields:
      - name: id
        type: int
      - name: name
        type: String

