name: customer-load
isActive: true
sourceConfigPath: source-config.yaml
targetConfigPath: target-config.yaml
processorConfigPath: processor-config.yaml
recoveryPolicy: rerun-from-start
steps:
  - name: customers-step
    source: Customers
    target: Customers
