targets:
  - format: xml
    targetName: Customers
    filePath: output/customers-custom-steps.xml
    rootElement: Customers
    recordElement: Customer
    fields:
      - name: id
        type: int
      - name: name
        type: String
      - name: email
        type: String

