name: xml-to-json-events
sourceConfigPath: source-config.yaml
targetConfigPath: target-config.yaml
processorConfigPath: processor-config.yaml
steps:
  - name: events-xml-to-json-step
    source: Events
    target: EventsJson

