type: default
mappings:
  - source: Events
    target: EventsJson
    fields:
      - from: eventCode
        to: eventCode
      - from: eventTime
        to: eventTime
      - from: description
        to: description
      - from: sourceSystem
        to: sourceSystem

