sources:
  - format: csv
    sourceName: Customers
    filePath: input/Customers-bad.csv
    delimiter: ","
    fields:
      - name: id
        type: int
      - name: name
        type: String
      - name: email
        type: String

