targets:
  - format: xml
    targetName: Customers
    filePath: output/customers.xml
    rootElement: Customers
    recordElement: Customer
    fields:
      - name: id
        type: int
      - name: name
        type: String
      - name: email
        type: String

  - format: xml
    targetName: Departments
    filePath: output/departments.xml
    rootElement: Departments
    recordElement: Department
    fields:
      - name: id
        type: int
      - name: name
        type: String

