name: xml-nested-to-csv-to-nested-xml-archive-e2e
sourceConfigPath: source-config.yaml
targetConfigPath: target-config.yaml
processorConfigPath: processor-config.yaml
recoveryPolicy: rerun-from-start
steps:
  - name: nested-xml-to-csv-step
    source: TagValidationSource
    target: TagValidationCsvIntermediate
  - name: csv-to-nested-xml-step
    source: TagValidationCsvIntermediate
    target: TagValidationNestedXml

