sources:
  - format: csv
    sourceName: Customers
    packageName: com.etl.generated.job.csvtosqlserver.source
    filePath: ../../demo-input/Customers.csv
    delimiter: ","
    fields:
      - name: id
        type: int
      - name: name
        type: String
      - name: email
        type: String

