targets:
  - format: csv
    targetName: EventsCsv
    filePath: output/events-output.csv
    delimiter: ","
    fields:
      - name: eventCode
        type: String
      - name: eventTime
        type: String
      - name: description
        type: String
      - name: sourceSystem
        type: String

