sources:
  - format: xml
    sourceName: TagValidationSource
    packageName: com.etl.generated.job.xmlnestedtocsvtagvalidation.source
    filePath: input/nested-sample.xml
    rootElement: TagValidationList
    recordElement: TVLTagDetails
    flatteningStrategy: NestedXml
    modelDefinitionPath: definitions/nested-source-model.yaml
    fields:
      - name: HomeAgencyID
        type: String

