targets:
  - format: csv
    targetName: TagValidationCsv
    packageName: com.etl.generated.job.xmlnestedtocsvtagvalidation.target
    filePath: target/tag-validation-export.csv
    delimiter: ","
    fields:
      - name: homeAgencyId
        type: String
      - name: tagAgencyId
        type: String
      - name: tagSerialNumber
        type: String
      - name: plateNumber
        type: String
      - name: plateCountry
        type: String
      - name: plateState
        type: String
      - name: accountNumber
        type: String


